// Code generated by "stringer -type=ServerClientEnum --linecomment -output namespace.enum_strings.go"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[serverEvent-0]
	_ = x[clientEvent-1]
}

const _ServerClientEnum_name = "serverclient"

var _ServerClientEnum_index = [...]uint8{0, 6, 12}

func (i ServerClientEnum) String() string {
	if i >= ServerClientEnum(len(_ServerClientEnum_index)-1) {
		return "ServerClientEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServerClientEnum_name[_ServerClientEnum_index[i]:_ServerClientEnum_index[i+1]]
}
